import "react-big-calendar/lib/css/react-big-calendar.css";
import "./globals.css";

// import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from "@/components/i18n";
import { Header } from "@/components";
import type { Metadata } from "next";
// Using system fonts instead of Google Fonts

export const metadata: Metadata = {
  title: "Menu Management",
  description: "Generated by create next app",
};

export default function AppSectionLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className="min-h-dvh bg-background text-foreground antialiased"
        style={{ fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif' }}
      >
        <LanguageProvider>
          <ThemeProvider>
            <div className="min-h-dvh bg-background text-foreground">
              <Header />
              <main className="flex-1 pt-16">{children}</main>
            </div>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
